### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by alegenyas** [loot/skyrim#175] opened 2018-02-25 13:14 UTC
[15:18:48.815860] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[15:18:48.878260] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[15:18:50.885517] [warning]: No masterlist present at C:\Users\Aleksey\AppData\Local\LOOT\Skyrim\masterlist.yaml
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1756043/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2018-02-25 13:20
I'm closing loot/loot.github.io#63 in favour of this one since it's in the right place. Please don't file any more duplicate issues, one more and I'll just block you for spamming.

As I said in the other issue thread, have you tried updating your masterlist?

**Comment by alegenyas** [comment] 2018-02-25 13:24
[15:18:48.815860] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[15:18:48.878260] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[15:18:50.885517] [warning]: No masterlist present at C:\Users\Aleksey\AppData\Local\LOOT\Skyrim\masterlist.yaml

**Comment by Ortham** [comment] 2018-02-25 13:32
Please see [How To Report Issues Helpfully](http://loot.github.io/docs/help/How-To-Report-Issues-Helpfully.html), particularly the bit about enabling debug logging.

**Comment by alegenyas** [comment] 2018-02-25 14:42
Всем спасибо проблема решена. Причина в повреждении  MSVC 2015 x86 redistributable, после восстановления MSVC 2015 x86 redistributable —  заработало.25.02.2018, 18:24, "Aleksey Yastrebkov" <alegenyas@yandex.com>:Yes. Had tried. When updating, it gives an error: look at the screenshot  25.02.2018, 18:20, "Oliver Hamlet" <notifications@github.com>:I'm closing loot/loot.github.io#63 in favour of this one since it's in the right place. Please don't file any more duplicate issues, one more and I'll just block you for spamming.As I said in the other issue thread, have you tried updating your masterlist?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Ortham** [comment] 2018-02-25 15:30
Closing this as the issue is fixed.

**Closed as completed by Ortham** 2018-02-25 15:30 UTC
