### ISSUE TITLE
Error no. 140358 please help

### ISSUE THREAD

**Issue by AAMEN716** [loot/skyrim#179] opened 2018-04-27 01:22 UTC
this didn't happen before i don't know if it's the metadata or the application itself

i Manged to fix this be enabling a profile in NMM that had [KJ Tattoos - Overlay Plugins for RaceMenu](https://www.nexusmods.com/skyrim/mods/50032) disabled .

 even disabling the plugin didn't help i had to disable the mod it's self

here is the LOOTDebugLog :

> [22:37:55.209564] [warning]: Chromium console message: Styling master document from stylesheets defined in HTML Imports is deprecated, and is planned to be removed in M65, around March 2018. Please refer to https://goo.gl/EGXzpw for possible migration paths.
[22:37:55.331654] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[22:37:58.072369] [error]: Exception while executing query: No plugin "e:\The Elder Scrolls V - Skyrim\Data\Skyrim.esm" exists.
[22:38:01.736987] [error]: Exception while executing query: No plugin "e:\The Elder Scrolls V - Skyrim\Data\Skyrim.esm" exists.
[22:38:01.738345] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 1: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:1:140358)

[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1953518/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2018-04-27 07:17
LOOT can't find Skyrim.esm, check that it's where LOOT's expecting to find it.

**Comment by pStyl3** [comment] 2018-05-10 13:35
Since @AAMEN716 mentioned KJ Tattoos, this could be related to [this issue](https://github.com/loot/loot/issues/787) .. though the DebugLog doesn't mention it.

**Comment by Ortham** [comment] 2018-05-27 07:19
Closing this bug report as it was filed for an old release and has not been reproduced on more recent releases of LOOT. If the issue can be replicated on the most recent release, this can be reopened.

**Closed as completed by Ortham** 2018-05-27 07:19 UTC
Labels: awaiting-feedback
