### ISSUE TITLE
Erm, i've got a problem here. I hope that I filled everything correctly

### ISSUE THREAD

**Issue by Madman505** [loot/skyrim#173] opened 2018-02-24 19:30 UTC
I don't know, everything worked fine before, but something gone wrong. And there is "No masterlist present" error.
P.S.: Sorry for my bad english.
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1754784/LOOTDebugLog.txt)

**Comment by pStyl3** [comment] 2018-02-25 07:30
Update LOOT to version 0.12.4, install all recommended Windows updates and make sure that you [enable TLS 1.2 support](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-a-default-secure-protocols-in) to support updating the masterlists from LOOT's official repositories on GitHub.

This is a duplicate of #882.

**Closed as completed** 2018-02-25 08:50 UTC
Labels: duplicate

**Comment by Madman505** [comment] 2018-02-25 12:00
You damn right. It works now. Thank you!
