### ISSUE TITLE
MASTERLIST NOT LOADING error message

### ISSUE THREAD

**Issue by Japamam** [loot/skyrim#172] opened 2018-02-24 00:29 UTC
Since yesterday my loot downt owrk properly givng a error message when i try to sort. There is the log plz help.
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1753640/LOOTDebugLog.txt)

**Comment by Japamam** [comment] 2018-02-24 00:57
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1753677/LOOTDebugLog.txt)
This one is more complete, same error

**Comment by Ortham** [comment] 2018-02-24 07:09
This is a duplicate of loot/loot#882.

**Closed as completed by Ortham** 2018-02-24 07:09 UTC
Labels: duplicate
