### ISSUE TITLE
No Masterlist present

### ISSUE THREAD

**Issue by lharchmage** [loot/skyrim#170] opened 2018-02-23 18:19 UTC
Keeps coming up no Masterlist present 
I Made sure it could go through the firewall. Tried uninstall and reinstall. Nothing.
I thought maybe it was just an out of date LOOt issue so I uninstalled the old program and installed the latest version.  
am very computer illiterate so I will also copy and paste the logs Just in case I really screwed up So sorry for the inconvenience.
[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1752685/LOOTDebugLog.txt)
[13:09:18.875201] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
[13:09:48.423201] [warning]: No masterlist present at C:\Users\jim\AppData\Local\LOOT\Skyrim\masterlist.yaml
[13:09:53.200201] [error]: Exception while executing query: Git operation failed. Details: -17; unknown certificate check failure: libgit2 error
[13:09:53.200201] [error]: Chromium console message from http://loot/ui/js/handlePromiseError.js at line 14: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/js/query.js:43:16)
Sorry Folks I appreciate the help

**Comment by Ortham** [comment] 2018-02-23 18:29
This is a duplicate of loot/loot#882.

**Closed as completed by Ortham** 2018-02-23 18:29 UTC
Labels: duplicate

**Comment by lharchmage** [comment] 2018-02-23 18:50
Sorry New to Github Thank You Sir!!! I really appreciate it and Your LOOt is awesome..(usually :) )
