### ISSUE TITLE
mod order not sorted: Oh no, something went wrong! You can check your LOOTDebugLog.txt

### ISSUE THREAD

**Issue by drougr** [loot/skyrim#167] opened 2018-02-13 12:01 UTC
Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
I have used 'duel wield parrying' mod over past years.
I just uninstall and reinstall new version of LOOT and all i have done is Installing mods like below:
Uninstalling duel wield parrying doesn't help me and In debuglog, the sepecific dll file has not been contained in duel wield parrying mod.
Thank you

[LOOTDebugLog.txt](https://github.com/loot/skyrim/files/1719782/LOOTDebugLog.txt)

**Comment by Ortham** [comment] 2018-02-13 21:38
This is a duplicate of #166, see that issue for details.

**Closed as completed by Ortham** 2018-02-13 21:38 UTC
Labels: duplicate
